### ISSUE TITLE
ICUE COMMANDER CORE XT SUPPORT

### ISSUE THREAD

**Issue by Frambooisier** [MisterZ42/corsair-cpro#1]
hello,

is there a possibility that commander core xt would work with this driver? Is there anything I could do to help implement it?

**Comment by MisterZ42** [comment]
Hello,

after looking a bit into it, there seems to be no simple solution. It probably should go in a new separate driver. The protocol seems to be quite different.

**Comment by Frambooisier** [comment]
I specifically bought this device because I read the wonderful news about the implementation of your driver to the Linux kernel(yay). The silly mistake I did not pay enough attention to see that commander core xt is not the same as commander pro. Is there anything that could be done about it? Do you even consider implementing the driver for core XT or its a burden you are not willing to take?

**Comment by MisterZ42** [comment]
Because the protocol is different and I do not have this device, I cannot help you. Sorry. Maybe check out liquidctl. There is some support for this device.
