### ISSUE TITLE
add support for iCUE Corsair Commander Pro XT

### ISSUE THREAD

**Issue by dankamongmen** [MisterZ42/corsair-cpro#4]
liquidctl has recently added support for setting and reading the 6 fans and 2 temperature sensors of the Corsair iCUE Commander Core XT (1b1c:0c2a). with the USB protocol decoded in that project, it ought not be too difficult to add support for this controller to this driver. i'd like to go ahead and do so. if this isn't the best place to collaborate with you, please redirect me.

i've done some kernel dev before.

thanks!

**Comment by MisterZ42** [comment]
Looking at the protocol of the Commander Core XT, it seems, this one uses hid report ids and quite a different protocol. (Anyway, the Commander Pro seems to be the odd one out here)
You are welcome to fork the driver and add your implementation. I would be happy to merge it.
If you find, that most of the code needs to be rewritten, it would seem worth to consider putting this into a separate driver.
Best Wishes!

**Comment by dankamongmen** [comment]
> Looking at the protocol of the Commander Core XT, it seems, this one uses hid report ids and quite a different protocol. (Anyway, the Commander Pro seems to be the odd one out here) You are welcome to fork the driver and add your implementation. I would be happy to merge it. If you find, that most of the code needs to be rewritten, it would seem worth to consider putting this into a separate driver. Best Wishes!

that's a good point. where are you looking at the protocol? liquidctl or something else? i'm not aware of any public documentation.

**Comment by MisterZ42** [comment]
Just looked at liquidctl. Sadly, there is no official documentation.
