### ISSUE TITLE
Add support for Commander Core

### ISSUE THREAD

**Issue by Grooty12** [MisterZ42/corsair-cpro#5]
Would it be possible or is it like with the Commander Core XT not possible?
I would be happy to try and write a Commander Core myself, but I don't think I'm skilled enough with either C or kernel-writing to do it.

**Comment by MisterZ42** [comment]
The Commander Core XT is quite different from the Commander Pro. This should probably go into a separate driver. But I don't have this device, so I cannot develop and test a driver in good conscience. I am sorry.

**Comment by Grooty12** [comment]
No problem. What resources did you use to create this driver, and how hard was it?

**Comment by MisterZ42** [comment]
- Find out, how the protocol works. (I used Wireshark with a Windows VM)
- Take a look at a few drivers in the hwmon subsystem.
- Read (the relevant parts of) the official Linux Kernel Documentation. It is a lot of mandatory reading, but quite interesting.
