### ISSUE TITLE
Phantom spikes in fan rpm

### ISSUE THREAD

**Issue by DrTron** [MisterZ42/corsair-cpro#6]
Hello!
I run a corsiar-cpro controller on the latest github version on a Debian 11 on kernel 5.10.0-23-amd64.

I have run the controller for more than a year now, but only recently one 3-pin fan started showing erratic rpm spikes. The fan itself does not spin up, it's just the rpm reading that is off.

During troubleshooting I replaced the fan, same issue. I further moved the fan from the fan1 connector to the fan5 connector, and the spikes stopped. However, now the 3-pin fan connected to the fan2 header shows these spikes.

Any idea?

![image](https://github.com/MisterZ42/corsair-cpro/assets/3955162/fae979b3-ed45-4bfd-8477-343a9b222e11)

**Comment by MisterZ42** [comment]
- Can you show me the output of "dmesg | grep -i corsair"?
- Do you use any other software which uses the controller (e.g. openrgb)
You can check with "lsof /dev/hidrawX" (the correct hidraw-device should be shown in the previous command.
- Maybe there could be some voltage spikes in the cables on the sensor pin or something inside the controller. You could check with the official windows software, if the problem persists?
- Which software do you use for showing the graph / controlling the fan speed? IMO very unlikely, but maybe there could be a problem there?

**Comment by DrTron** [comment]
Sure.
`[    1.415230] usb 1-7: Manufacturer: Corsair`
`[    2.078510] hid-generic 0003:1B1C:0C10.0001: hiddev0,hidraw0: USB HID v1.11 Device [Corsair Commander PRO] on usb-0000:00:14.0-7/input0`
`[    4.719904] corsair_cpro: loading out-of-tree module taints kernel.`
`[    4.719965] corsair_cpro: module verification failed: signature and/or required key missing - tainting kernel`
`[    4.720912] corsair-cpro 0003:1B1C:0C10.0001: hidraw0: USB HID v1.11 Device [Corsair Commander PRO] on usb-0000:00:14.0-7/input0`

As the module is unsigned, that is expected.
No other controller for RGB or such, lsof /dev/hidraw0 does not return anything.
The system is Linux only, so no real good way to check with the Windows software. But I doubt it's a cable since the spikes moved to another fan when I disconnected fan1.
I read the values from /sys/class/hwmon every two minutes and write them into an influx database. Plottig is done with Grafana. It's always only one datapoint that's high.
I use a little shell script to control speed (https://github.com/kevinlekiller/shell_scripts/tree/main/fancontrol), but it's unchanged since way before the spikes began. But the fans are always running at minimum speed, so the control script doesn't do much usually.
I also doubt the spikes are real, as they go up way past 2000 rpm, and the fans max out at 1000 anyhow.

**Comment by MisterZ42** [comment]
Do you get any errors, while reading from the device before or after the spikes (could return e.g. -ENODATA)
Was there any kernel update or any other update, that could have caused this?
If you have the time you could try using liquidctl while having the kernel driver unloaded. It should read the data directly through hidraw and could give a hint, whether this is a problem with the driver or any other problem.

**Comment by DrTron** [comment]
No errors, just the wrong rpm value. As further proof those can't be real rpm's, the fan just hit a new record at 7300rpm.
I obviously update the kernel when a new one is available, but those have all been bugfixes for the 5.10 kernel. No major version change.

I can give liquidctl a try, I'll need to modify my scripts to get the data from that, then, but that's doable.
It does say on their Readme for the Commander Pro that it "can leverage the hwmon driver", whatever that may mean exactly.

**Comment by DrTron** [comment]
Update: liquidctl shows the same rpm spikes reading the controller directly and with the kernel module unloaded.
So it's definitively the controller causing this, and not the kernel module.

**Comment by MisterZ42** [comment]
Thank you for testing.
Sorry for not being able to help you with this.
You could try updating the firmware of the controller. But this only works with the official Corsair software under windows.
Good luck!

**Comment by DrTron** [comment]
Thanks.
From what I was able to find out, it is already the lastest firmware. Well, if you call a release date sometime in 2019 "latest".
