### ISSUE TITLE
Add support for the Corsair Commander Pro XT (VID 0x1b1c, PID 0x0c2a)

### ISSUE THREAD

**Issue by antiduh** [MisterZ42/corsair-cpro#9]
Hello,

It looks like the original Commander Pro (PID 0x0c10) is no longer being made by Corsair, and availability is limited. 

Would you be able to add support for the Commander Pro XT?
```
computah(/home/demouser) # lsusb
Bus 001 Device 004: ID 1b1c:0c2a Corsair CORSAIR iCUE COMMANDER CORE XT
...
```

It has 6 fan ports, 6 RGB Hub ports, and 2 temp sensor ports.

I own one and can test changes for you; if you'd like I can buy you one and ship it to you too. I'm going to take a crack at modifying the source code myself to add support. I have very little linux kernel experience though, so I expect I'll make mistakes.

**Comment by MisterZ42** [comment]
The XT has a completely different protocol compared to the Commander Pro. A whole new driver should probably be written for it. For now I don't have the time to do this. Sorry.
